version: '3'
services:
  angular:
    build:
      context: .
      dockerfile: Dockerfile
    restart: "always"
    networks:
      - "traefik-proxy"
    volumes:
      - .:/app
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik-proxy"
      - "traefik.http.routers.react.rule=Host(`${DOMAIN}`) && PathPrefix(`/`)"
      - "traefik.http.routers.react.entrypoints=websecure"
      - "trafeik.http.routers.react.tls=true"
      - "traefik.http.routers.react.tls.certresolver=production"
      - "traefik.http.services.react.loadbalancer.server.port=80"

networks:
  traefik-proxy:
    external: true
      
